updates for write_yp_config, sge_execd
git-svn-id: svn+ssh://repository/svn/clustersoftware@179 44af9490-3b78-11e1-98d3-d193acd27c9c

diff --git a/sgeexecd b/sgeexecd
--- a/sgeexecd
+++ b/sgeexecd
@@ -54,25 +54,22 @@ PATH=/bin:/usr/bin:/sbin:/usr/sbin
 
 #---------------------------------------------------------------------------
 # The following lines provide the necessary info for adding a startup script
-# according to the Linux Standard Base Specification (LSB) 1.0.0 which can
+# according to the Linux Standard Base Specification (LSB) which can
 # be found at:
 #
-#    http://www.linuxbase.org/spec/gLSB/gLSB/sysinit.html
-#
-# See also
-#
-#    http://www.suse.de/~grimmer/Package-Conventions/index.html
+#    http://www.linuxfoundation.org/spec/booksets/LSB-Core-generic/LSB-Core-generic/initscrcomconv.html
 #
 ### BEGIN INIT INFO
-# Provides:       sgeexecd 
-# Required-Start: $network
-# Should-Start: package-client
+# Provides:       sgeexecd.cluster
+# Required-Start: $network $remote_fs
 # Required-Stop:
 # Default-Start:  3 5
 # Default-Stop: 0 1 2 6
 # Description:  start Grid Engine execd 
 ### END INIT INFO
+# chkconfig: 35 96 2
 #---------------------------------------------------------------------------
+
 #---------------------------------------------------------------------------
 # FixServices
 # add entries to /etc/services if necessary
@@ -82,14 +79,14 @@ FixServices() {
     cat /etc/services | grep -a -v sge_execd | grep -a -v sge_qmaster > /tmp/bla
     mv /tmp/bla /etc/services
     cat /etc/services | grep -a sge_execd > /dev/null || {
-	logger "modifying /etc/services for sgeexecd"
-	if [ -f /etc/sysconfig/sge/qmaster_port ] ; then
-	    echo "sge_qmaster     $(cat /etc/sysconfig/sge/qmaster_port)" >> /etc/services
-	    echo "sge_execd       $(cat /etc/sysconfig/sge/execd_port)" >> /etc/services
-	else
-	    echo "sge_qmaster     6444/tcp" >> /etc/services
-	    echo "sge_execd       6445/tcp" >> /etc/services
-	fi
+        logger "modifying /etc/services for sgeexecd"
+        if [ -f /etc/sysconfig/sge/qmaster_port ] ; then
+            echo "sge_qmaster     $(cat /etc/sysconfig/sge/qmaster_port)" >> /etc/services
+            echo "sge_execd       $(cat /etc/sysconfig/sge/execd_port)" >> /etc/services
+        else
+            echo "sge_qmaster     6444/tcp" >> /etc/services
+            echo "sge_execd       6445/tcp" >> /etc/services
+        fi
     }
 }
 # FixLimits
@@ -103,8 +100,8 @@ FixLimits() {
 
 FixLink() {
     if [ ! -L /usr/sbin/rcsgeexecd ] ; then
-	logger "Creating link for sgeexecd"
-	ln -s $0 /usr/sbin/rcsgeexecd
+        logger "Creating link for sgeexecd"
+        ln -s $0 /usr/sbin/rcsgeexecd
     fi
 }
 
@@ -113,65 +110,149 @@ if [ -f /etc/sge_cell -a -f /etc/sge_root ] ; then
     SGE_CELL=`cat /etc/sge_cell` ; export SGE_CELL
 else
     echo "SGE Environment not set, exiting..."
-    exit -1 
+    exit -1
 fi
 
 FixServices
 FixLimits
 FixLink
 
+unset SGE_QMASTER_PORT 
+unset SGE_EXECD_PORT
+
 unset CODINE_ROOT GRD_ROOT COD_CELL GRD_CELL
 
-SGE_ARCH=`$SGE_ROOT/util/arch`
-shlib_path_name=`$SGE_ROOT/util/arch -lib`
-old_value=`eval echo '$'$shlib_path_name`
-if [ x$old_value = x ]; then
-   eval $shlib_path_name=$SGE_ROOT/lib/$SGE_ARCH
-else
-   eval $shlib_path_name=$old_value:$SGE_ROOT/lib/$SGE_ARCH
-fi
-export $shlib_path_name
+count=0
+while [ ! -d "$SGE_ROOT" -a $count -le 120 ]; do
+   count=`expr $count + 1`
+   sleep 1
+done
+
+ARCH=`$SGE_ROOT/util/arch`
+# library path setting required only for architectures where RUNPATH is not supported
+[ -d $SGE_ROOT/lib/$ARCH ] &&
+case $ARCH in
+sol*|lx*)
+   ;;
+*)
+   shlib_path_name=`$SGE_ROOT/util/arch -lib`
+   old_value=`eval echo '$'$shlib_path_name`
+   if [ x$old_value = x ]; then
+      eval $shlib_path_name=$SGE_ROOT/lib/$ARCH
+   else
+      eval $shlib_path_name=$old_value:$SGE_ROOT/lib/$ARCH
+   fi
+   export $shlib_path_name
+   ;;
+esac
+
+#---------------------------------------------------------------------------
+# DetectSMFService - sets service to a mask matching the name
+# $1 ... name
+#
+DetectSMFService()
+{
+   name=$1
+   service=""
+
+   if [ "$noSMF" = true ]; then
+      return
+   fi
+   #Otherwise we try is it's available of the system
+   if [ -f /lib/svc/share/smf_include.sh ]; then
+      . /lib/svc/share/smf_include.sh
+      smf_present
+      if [ $? -ne 0 ]; then
+         return
+      fi
+   else
+      return
+   fi
+
+   #Check we have cluster_name file
+   if [ ! -r "$SGE_ROOT/$SGE_CELL/common/cluster_name" ]; then
+      echo "Error: could not find $SGE_ROOT/$SGE_CELL/common/cluster_name!"
+      exit $SMF_EXIT_ERR_CONFIG
+   fi
+   #Cluster name must be unique
+   SGE_CLUSTER_NAME=`cat $SGE_ROOT/$SGE_CELL/common/cluster_name 2>/dev/null`
+   
+   service="svc:/application/sge/$name:$SGE_CLUSTER_NAME"
+
+   #Check if service exists
+   /usr/bin/svcs $service > /dev/null 2>&1
+   if [ $? -ne 0 ]; then
+      #No such service found in the system
+      service=""
+   fi
+}
+
+
+#---------------------------------------------------------------------------
+# ShutdownSMF
+#
+ShutdownSMF()
+{
+   if [ -z "$service" ]; then
+      #We don't have any such SMF service we use normal Shutdown
+      return
+   fi
+   pid=`/usr/bin/svcs -l -p $service | grep "/sge_execd$" | grep -v "^grep" | awk '{print $2}'`
+   if [ -n "$pid" ]; then
+      usingSMF="true"
+      /usr/sbin/svcadm disable -st $service
+   fi
+}
+
 
 #---------------------------------------------------------------------------
 # Shutdown
-# Send SIGTERM to process name $1 with pid in file $2
+# Send SIGTERM (default) or signal $3 to process name $1 with pid in file $2
 #
-Shutdown() {
-    name=$1
-    pidfile=$2
-    if [ -f $pidfile ]; then
-	pid=`cat $pidfile`
-	$utilbin_dir/checkprog $pid $name > /dev/null
-	if [ "$?" = 0 ]; then
-	    kill -TERM $pid
-	fi
-    fi
+Shutdown()
+{
+   name=$1
+   pidfile=$2
+   signal="-TERM"
+   
+   if [ $# = 3 ]; then 
+      signal="-$3"
+   fi 
+   if [ -f $pidfile ]; then
+      pid=`cat $pidfile`
+      $utilbin_dir/checkprog $pid $name > /dev/null
+      if [ "$?" = 0 ]; then
+         kill $signal $pid
+         return $?
+      fi
+   fi
 }
 
 
 #---------------------------------------------------------------------------
 # GetPathToBinaries
 #    echo the name of the bin_dir on this system
-#    The check is fullfilled if we can access the qstat binary
+#    The check is fulfilled if we can access the qstat binary
 #    echo "none" if we can't determine the binary path
-GetPathToBinaries() {
-    cfgname=$SGE_ROOT/$SGE_CELL/common/bootstrap
-    
-    base=none
-    
-    if [ -f $cfgname ]; then
-	base=`grep binary_path $cfgname | awk '{ print $2 }'`
-	if [ -f $base/qstat ]; then
-	    :
-	elif [ -f $SGE_ROOT/util/arch ]; then
-	    arch=`$SGE_ROOT/util/arch`
-	    if [ -f $base/$arch/qstat ]; then
-		base=$base/$arch
-	    fi
-	fi
-    fi
-    
-    echo $base
+GetPathToBinaries()
+{
+   cfgname=$SGE_ROOT/$SGE_CELL/common/bootstrap
+
+   base=none
+
+   if [ -f $cfgname ]; then
+      base=`grep binary_path $cfgname | awk '{ print $2 }'`
+      if [ -f $base/qstat ]; then
+         :
+      elif [ -f $SGE_ROOT/util/arch ]; then
+         arch=`$SGE_ROOT/util/arch`
+         if [ -f $base/$arch/qstat ]; then
+               base=$base/$arch
+         fi
+      fi
+   fi
+
+   echo $base
 }
 
 
@@ -179,88 +260,91 @@ GetPathToBinaries() {
 # GetAdminUser
 #    echo the name of the admin user on this system
 #    echo "root" if admin user retrieval fails
-GetAdminUser() {
-    cfgname=$SGE_ROOT/$SGE_CELL/common/bootstrap
-    user=none
-    
-    if [ -f $cfgname ]; then
-	user=`grep admin_user $cfgname | awk '{ print $2 }'`
-    fi
-    
-    if [ `echo $user|tr "A-Z" "a-z"` = "none" ]; then
-	user=root
-    fi
-    echo $user
+GetAdminUser()
+{
+   cfgname=$SGE_ROOT/$SGE_CELL/common/bootstrap
+   user=none
+
+   if [ -f $cfgname ]; then
+      user=`grep admin_user $cfgname | awk '{ print $2 }'`
+   fi
+
+   if [ `echo $user|tr "[A-Z]" "[a-z]"` = "none" ]; then
+      user=root
+   fi
+   echo $user
 }
 
 #---------------------------------------------------------------------------
 # GetPathToUtilbin
-#    echo the path to the binaires in utilbin
-#    The check is fullfilled if we can access the "gethostname" binary
+#    echo the path to the binaries in utilbin
+#    The check is fulfilled if we can access the "gethostname" binary
 #    echo "none" if we can't determine the binary path
 #
-GetPathToUtilbin() {
-    base=none
-    
-    if [ -f $SGE_ROOT/util/arch ]; then
-	utilbindir=$SGE_ROOT/utilbin
-	
-	arch=`$SGE_ROOT/util/arch`
-	if [ -f $utilbindir/$arch/gethostname ]; then
-	    base=$utilbindir/$arch
-	fi
-    fi
-    
-    echo $base
+GetPathToUtilbin()
+{
+   base=none
+
+   if [ -f $SGE_ROOT/util/arch ]; then
+      utilbindir=$SGE_ROOT/utilbin
+
+      arch=`$SGE_ROOT/util/arch`
+      if [ -f $utilbindir/$arch/gethostname ]; then
+         base=$utilbindir/$arch
+      fi
+   fi
+
+   echo $base
 }
 
 
 #---------------------------------------------------------------------------
 # GetExecdSpoolDir
 # get the execution daemon spooling dir from configuration
-GetExecdSpoolDir() {
-    EXECD_SPOOL_DIR=`$bin_dir/qconf -sconf $UQHOST | grep execd_spool_dir | awk '{ print $2 }'`
-    if [ "$EXECD_SPOOL_DIR" = "" ]; then
-	EXECD_SPOOL_DIR=`$bin_dir/qconf -sconf | grep execd_spool_dir | awk '{ print $2 }'`
-    fi
-
+GetExecdSpoolDir()
+{
+   EXECD_SPOOL_DIR=`$bin_dir/qconf -sconf $UQHOST 2>/dev/null |
+      grep execd_spool_dir | awk '{ print $2 }'`
+   if [ "$EXECD_SPOOL_DIR" = "" ]; then
+      EXECD_SPOOL_DIR=`$bin_dir/qconf -sconf | grep execd_spool_dir | awk '{ print $2 }'`
+   fi
 }
 
 #---------------------------------------------------------------------------
-usage() {
-    echo "Grid Engine start/stop script. Valid parameters are:"
-    echo ""
-    echo "   (no parameters): start qmaster and execution daemon if applicable"
-    echo "   \"start\"        dto."
-    echo "   \"stop\"         shutdown local Grid Engine processes and jobs"
-    echo "   \"softstop\"     shutdown local Grid Engine processes (no jobs)"
-    echo "                    host and restart it on this host"
-    echo "                    Migration only works if this host is an admin host"
-    echo ""
-    echo "Only one of the parameters \"start\", \"stop\" or \"softstop\" is allowed."
-    echo "Only one of the parameters beginning  with \"-\" is allowed." 
-    echo
-    echo "Default argument is \"start\" for all components."
-    echo "Default for \"stop\" is shutting down all components."
-    echo
-    exit 1
+usage()
+{
+   echo "Grid Engine start/stop script. Valid parameters are:"
+   echo ""
+   echo "   (no parameters): start execution daemon if applicable"
+   echo "   \"start\"        ditto."
+   echo "   \"stop\"         shutdown local Grid Engine processes and jobs"
+   echo "   \"softstop\"     shutdown local Grid Engine processes (no jobs)"
+   echo "   \"restart\"      restart local Grid Engine processes (keeping jobs)"
+   echo "   \"-nosmf\"       force no SMF"
+   echo ""
+   echo "Only one of \"start\", \"stop\", \"restart\", or \"softstop\" is allowed."
+   echo
+   echo "Default argument is \"start\" for all components."
+   echo "Default for \"stop\" is shutting down all components."
+   echo
+   exit 1
 }
 
 create_meta_block() {
     if [ -d /var/lib/meta-server ] ; then
-	rm -f /var/lib/meta-server/sge_execd
-	echo "NAME = sge_execd" >> /var/lib/meta-server/sge_execd
-	echo "EXE_NAME = sge_execd" >> /var/lib/meta-server/sge_execd
-	echo "START_COMMAND = /etc/init.d/sgeexecd start" >> /var/lib/meta-server/sge_execd
-	echo "STOP_COMMAND = /etc/init.d/sgeexecd stop" >> /var/lib/meta-server/sge_execd
-	echo "CHECK_MEMORY = 1" >> /var/lib/meta-server/sge_execd
-	echo "NEED_ANY_PIDS = 1" >> /var/lib/meta-server/sge_execd
+        rm -f /var/lib/meta-server/sge_execd
+        echo "NAME = sge_execd" >> /var/lib/meta-server/sge_execd
+        echo "EXE_NAME = sge_execd" >> /var/lib/meta-server/sge_execd
+        echo "START_COMMAND = /etc/init.d/sgeexecd start" >> /var/lib/meta-server/sge_execd
+        echo "STOP_COMMAND = /etc/init.d/sgeexecd stop" >> /var/lib/meta-server/sge_execd
+        echo "CHECK_MEMORY = 1" >> /var/lib/meta-server/sge_execd
+        echo "NEED_ANY_PIDS = 1" >> /var/lib/meta-server/sge_execd
     fi
 }
 
 delete_meta_block() {
     if [ -d /var/lib/meta-server ] ; then
-	rm -f /var/lib/meta-server/sge_execd
+        rm -f /var/lib/meta-server/sge_execd
     fi
 }
 
@@ -269,68 +353,118 @@ delete_meta_block() {
 #
 
 if [ "$#" -gt 2 -o "$1" = "-h" -o "$1" = "help" ]; then
-    usage
+   usage
 fi
 
 startup=true
 execd=true
-qstd=false
 softstop=false
+stop=false
+noSMF=false
 
-for i in $* ; do
-    if [ "$i" = start ]; then
-	startup=true
-	create_meta_block
-    elif [ "$i" = stop ]; then
-	delete_meta_block
-	startup=false
-    elif [ "$i" = softstop ]; then
-	delete_meta_block
-	startup=false
-	softstop=true
-    else
-	usage
-    fi
+for i in $*; do
+   if [ "$i" = start ]; then
+      startup=true
+   elif [ "$i" = stop ]; then
+      stop=true
+      startup=false
+   elif [ "$i" = softstop ]; then
+      softstop=true
+      startup=false
+   elif [ "$i" = -nosmf ]; then
+      noSMF=true
+   elif [ "$i" = restart ]; then
+      startup=true
+      softstop=true
+   else
+      usage
+   fi
 done
 
 bin_dir=`GetPathToBinaries`
 if [ "$bin_dir" = "none" ]; then
-    echo "can't determine path to Grid Engine binaries"
-    exit 1
+   echo "can't determine path to Grid Engine binaries"
+   exit 5  # LSB compliant exit status - program is not installed
 fi
 
 utilbin_dir=`GetPathToUtilbin`
 if [ "$utilbin_dir" = "none" ]; then
-    echo "can't determine path to Grid Engine utility binaries"
-    exit 1
+   echo "can't determine path to Grid Engine utility binaries"
+   exit 5  # LSB compliant exit status - program is not installed
 fi
 
+# HOST is the aliased name (SGE name)
+# UQHOST is the local host name (unqualified name)
 HOST=`$utilbin_dir/gethostname -aname`
-UQHOST=`$utilbin_dir/gethostname -aname | cut -f1 -d.`
+UQHOST=`$utilbin_dir/gethostname -name | cut -f1 -d.`
 
-if [ "$startup" = true ]; then
+DetectSMFService execd
 
-   # execution daemon is started on this host!
-
-      echo "   starting sge_execd"
-      exec 1>/dev/null 2>&1
-      $bin_dir/sge_execd
-else
+if [ $stop = true -o $softstop = true ]; then
+   # Shutdown execution daemon
    if [ $execd = true ]; then
-      # Shutdown execution daemon
       GetExecdSpoolDir
       execd_spool_dir=$EXECD_SPOOL_DIR/$UQHOST
 
-      # Send SIGTERM to execd
+      usingSMF=false
       echo "   Shutting down Grid Engine execution daemon"
-      Shutdown sge_execd $execd_spool_dir/execd.pid
-
+      #We try to use SMF 
+      ShutdownSMF
+      #Otherwise we use normal shutdown
+      if [ "$usingSMF" != true ]; then
+         # Send SIGTERM to execd
+         Shutdown sge_execd $execd_spool_dir/execd.pid
+         ret=$?
+         if [ -f /var/lock/subsys/sgeexecd ]; then
+             uid=`$utilbin_dir/uidgid -uid` 
+             if [ "$uid" = "0" -a "$ret" = "0" ]; then
+                rm -f /var/lock/subsys/sgeexecd >/dev/null 2>&1
+             else
+                echo "Can't shut down execd!"
+                exit 1
+             fi
+         fi
+      fi
       if [ $softstop = false ]; then
-         # Send SIGTERM to all shepherds
-         for jobid in `ls $execd_spool_dir/active_jobs`; do
+         # Send SIGTERM to all shepherds (send SIGTSTP which is converted to SIGTERM by shepherd)
+         for jobid in `ls $execd_spool_dir/active_jobs 2>/dev/null`; do
             echo "   Shutting down Grid Engine shepherd of job $jobid"
-            Shutdown sge_shepherd $execd_spool_dir/active_jobs/$jobid/pid
+            Shutdown sge_shepherd $execd_spool_dir/active_jobs/$jobid/pid TSTP 
          done
       fi
    fi
+fi
+
+if [ "$startup" = true ]; then
+      #We want to use smf
+      if [ \( -z "$SMF_FMRI" -o "$SMF_FMRI" != "$service" \) -a -n "$service" ]; then
+         svcadm enable -st $service
+         exit $?
+      fi
+      # execution daemon is started on this host!
+      if [ "$SGE_EXECD_PORT" = "" ]; then
+         ping_port=`$utilbin_dir/getservbyname -number sge_execd`
+      else
+         ping_port=$SGE_EXECD_PORT
+      fi
+      echo "   starting sge_execd"
+      exec 1>/dev/null 2>&1
+      $bin_dir/sge_execd
+      [ $? -eq 0 -a -d /var/lock/subsys ] && touch /var/lock/subsys/sgeexecd
+
+      #Don't exit until daemon is up
+      $bin_dir/qping -info "$HOST" "$ping_port" execd 1 > /dev/null 2>&1
+      ret=$?
+      loop=0
+      while [ $ret -ne 0 -a $loop -ne 61 ]; do
+         sleep 1
+         $bin_dir/qping -info "$HOST" "$ping_port" execd 1 > /dev/null 2>&1
+         ret=$?
+         loop=`expr $loop + 1`
+      done
+      if [ $loop -eq 61 ]; then
+         echo "Execd did not start in 61 seconds!"
+         exit 1
+      fi
+      exit 0
 fi
