added 'status' to sgemaster / sgeexced startscript

diff --git a/sgeexecd b/sgeexecd
--- a/sgeexecd
+++ b/sgeexecd
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 #
-# SGE/SGEEE startup script
+# SGE startup script
 #
 #___INFO__MARK_BEGIN__
 ##########################################################################
@@ -43,12 +43,15 @@
 #                   and the shepherd. This only works if the execution daemon 
 #                   spool directory is in the default location.
 #       softstop    do not kill the shepherd process
+#       restart     equivalent to softstop followed by start
 #
 # Unix commands which may be used in this script:
 #    cat cut tr ls grep awk sed basename
 #
 # This script requires the script $SGE_ROOT/util/arch
-#
+# Customization can be placed in /etc/default/sgeexecd or
+# /etc/sysconfig/sgeexecd (according to OS conventions), which is sourced
+# after other setup.
 
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
 
@@ -60,50 +63,15 @@ PATH=/bin:/usr/bin:/sbin:/usr/sbin
 #    http://www.linuxfoundation.org/spec/booksets/LSB-Core-generic/LSB-Core-generic/initscrcomconv.html
 #
 ### BEGIN INIT INFO
-# Provides:       sgeexecd.cluster
+# Provides:       SGEEXEC
 # Required-Start: $network $remote_fs
-# Required-Stop:
+# Required-Stop: $network $remote_fs
 # Default-Start:  3 5
 # Default-Stop: 0 1 2 6
 # Description:  start Grid Engine execd 
 ### END INIT INFO
 # chkconfig: 35 96 2
 #---------------------------------------------------------------------------
-
-#---------------------------------------------------------------------------
-# FixServices
-# add entries to /etc/services if necessary
-#
-FixServices() {
-    # clear old ones
-    cat /etc/services | grep -a -v sge_execd | grep -a -v sge_qmaster > /tmp/.sge_srvc_$$
-    mv /tmp/.sge_srvc_$$ /etc/services
-    cat /etc/services | grep -a sge_execd > /dev/null || {
-        logger "modifying /etc/services for sgeexecd"
-        if [ -f /etc/sysconfig/sge/qmaster_port ] ; then
-            echo "sge_qmaster     $(cat /etc/sysconfig/sge/qmaster_port)" >> /etc/services
-            echo "sge_execd       $(cat /etc/sysconfig/sge/execd_port)" >> /etc/services
-        else
-            echo "sge_qmaster     6444/tcp" >> /etc/services
-            echo "sge_execd       6445/tcp" >> /etc/services
-        fi
-    }
-}
-# FixLimits
-# modifies resource limits; needed for infiniband
-#
-FixLimits() {
-    logger "setting limits for sgeexecd"
-    ulimit -H -l unlimited
-    ulimit -S -l unlimited
-}
-
-FixLink() {
-    if [ ! -L /usr/sbin/rcsgeexecd ] ; then
-        logger "Creating link for sgeexecd"
-        ln -s $0 /usr/sbin/rcsgeexecd
-    fi
-}
 
 if [ -f /etc/sge_cell -a -f /etc/sge_root ] ; then
     SGE_ROOT=`cat /etc/sge_root` ; export SGE_ROOT
@@ -113,14 +81,8 @@ else
     exit -1
 fi
 
-FixServices
-FixLimits
-FixLink
-
-unset SGE_QMASTER_PORT 
-unset SGE_EXECD_PORT
-
-unset CODINE_ROOT GRD_ROOT COD_CELL GRD_CELL
+SGE_QMASTER_PORT=6444; export SGE_QMASTER_PORT 
+SGE_EXECD_PORT=6445; export SGE_EXECD_PORT
 
 count=0
 while [ ! -d "$SGE_ROOT" -a $count -le 120 ]; do
@@ -145,6 +107,9 @@ sol*|lx*)
    export $shlib_path_name
    ;;
 esac
+
+[ -f /etc/default/sgeexecd ] && . /etc/default/sgeexecd
+[ -f /etc/sysconfig/sgeexecd ] && . /etc/sysconfig/sgeexecd
 
 #---------------------------------------------------------------------------
 # DetectSMFService - sets service to a mask matching the name
@@ -308,6 +273,7 @@ GetExecdSpoolDir()
    if [ "$EXECD_SPOOL_DIR" = "" ]; then
       EXECD_SPOOL_DIR=`$bin_dir/qconf -sconf | grep execd_spool_dir | awk '{ print $2 }'`
    fi
+   echo "$EXECD_SPOOL_DIR"
 }
 
 #---------------------------------------------------------------------------
@@ -320,6 +286,7 @@ usage()
    echo "   \"stop\"         shutdown local Grid Engine processes and jobs"
    echo "   \"softstop\"     shutdown local Grid Engine processes (no jobs)"
    echo "   \"restart\"      restart local Grid Engine processes (keeping jobs)"
+   echo "   \"status\"       status of the sgeexecd"
    echo "   \"-nosmf\"       force no SMF"
    echo ""
    echo "Only one of \"start\", \"stop\", \"restart\", or \"softstop\" is allowed."
@@ -330,23 +297,6 @@ usage()
    exit 1
 }
 
-create_meta_block() {
-    if [ -d /var/lib/meta-server ] ; then
-        rm -f /var/lib/meta-server/sge_execd
-        echo "NAME = sge_execd" >> /var/lib/meta-server/sge_execd
-        echo "EXE_NAME = sge_execd" >> /var/lib/meta-server/sge_execd
-        echo "START_COMMAND = /etc/init.d/sgeexecd start" >> /var/lib/meta-server/sge_execd
-        echo "STOP_COMMAND = /etc/init.d/sgeexecd stop" >> /var/lib/meta-server/sge_execd
-        echo "CHECK_MEMORY = 1" >> /var/lib/meta-server/sge_execd
-        echo "NEED_ANY_PIDS = 1" >> /var/lib/meta-server/sge_execd
-    fi
-}
-
-delete_meta_block() {
-    if [ -d /var/lib/meta-server ] ; then
-        rm -f /var/lib/meta-server/sge_execd
-    fi
-}
 
 #---------------------------------------------------------------------------
 # MAIN Procedure
@@ -359,12 +309,16 @@ fi
 startup=true
 execd=true
 softstop=false
+status=false
 stop=false
 noSMF=false
 
 for i in $*; do
    if [ "$i" = start ]; then
       startup=true
+   elif [ "$i" = status  ] ; then
+      status=true
+      startup=false
    elif [ "$i" = stop ]; then
       stop=true
       startup=false
@@ -398,13 +352,14 @@ fi
 HOST=`$utilbin_dir/gethostname -aname`
 UQHOST=`$utilbin_dir/gethostname -name | cut -f1 -d.`
 
+execd_run_dir=`GetExecdSpoolDir`/$UQHOST
+
 DetectSMFService execd
 
 if [ $stop = true -o $softstop = true ]; then
    # Shutdown execution daemon
    if [ $execd = true ]; then
-      GetExecdSpoolDir
-      execd_spool_dir=$EXECD_SPOOL_DIR/$UQHOST
+      execd_spool_dir=$execd_run_dir
 
       usingSMF=false
       echo "   Shutting down Grid Engine execution daemon"
@@ -413,7 +368,7 @@ if [ $stop = true -o $softstop = true ]; then
       #Otherwise we use normal shutdown
       if [ "$usingSMF" != true ]; then
          # Send SIGTERM to execd
-         Shutdown sge_execd $execd_spool_dir/execd.pid
+         Shutdown sge_execd $execd_run_dir/execd.pid
          ret=$?
          if [ -f /var/lock/subsys/sgeexecd ]; then
              uid=`$utilbin_dir/uidgid -uid` 
@@ -425,6 +380,27 @@ if [ $stop = true -o $softstop = true ]; then
              fi
          fi
       fi
+      # execution daemon is started on this host!
+      if [ "$SGE_EXECD_PORT" = "" ]; then
+         ping_port=`$utilbin_dir/getservbyname -number sge_execd`
+      else
+         ping_port=$SGE_EXECD_PORT
+      fi
+      # Wait while daemon is up
+      retries=0
+      while [ $retries -le 61 ]; do
+         $bin_dir/qping -info "$HOST" "$ping_port" execd 1 > /dev/null 2>&1
+         if [ $? -ne 0 ]; then
+            break
+         else
+            sleep 1
+            retries=`expr $retries + 1`
+         fi
+      done
+      if [ $retries -eq 61 ]; then
+         echo "Execd did not stop in 61 seconds!"
+         exit 1
+      fi
       if [ $softstop = false ]; then
          # Send SIGTERM to all shepherds (send SIGTSTP which is converted to SIGTERM by shepherd)
          for jobid in `ls $execd_spool_dir/active_jobs 2>/dev/null`; do
@@ -435,7 +411,28 @@ if [ $stop = true -o $softstop = true ]; then
    fi
 fi
 
+
+if [ "$status" = true ]; then
+     already_running=false
+      if [ -f /var/lock/subsys/sgeexecd ] ; then
+            already_running=true
+      fi
+     if [ "${already_running}" = true ] ; then
+        echo "running"
+        exit 0
+     else
+        echo "not running"
+        exit 1
+     fi
+fi
+
 if [ "$startup" = true ]; then
+      # Ensure the shepherd will run, e.g. not missing hwloc dynamic lib
+      if ! $bin_dir/sge_shepherd -help >/dev/null 2>&1; then
+          echo "sge_shepherd won't run -- dynamic library missing?"
+          exit 5
+      fi
+
       #We want to use smf
       if [ \( -z "$SMF_FMRI" -o "$SMF_FMRI" != "$service" \) -a -n "$service" ]; then
          svcadm enable -st $service
@@ -447,22 +444,23 @@ if [ "$startup" = true ]; then
       else
          ping_port=$SGE_EXECD_PORT
       fi
-      echo "   starting sge_execd"
+      echo "   Starting Grid Engine execution daemon"
       exec 1>/dev/null 2>&1
       $bin_dir/sge_execd
       [ $? -eq 0 -a -d /var/lock/subsys ] && touch /var/lock/subsys/sgeexecd
 
       #Don't exit until daemon is up
-      $bin_dir/qping -info "$HOST" "$ping_port" execd 1 > /dev/null 2>&1
-      ret=$?
-      loop=0
-      while [ $ret -ne 0 -a $loop -ne 61 ]; do
-         sleep 1
+      retries=0
+      while [ $retries -le 61 ]; do
          $bin_dir/qping -info "$HOST" "$ping_port" execd 1 > /dev/null 2>&1
-         ret=$?
-         loop=`expr $loop + 1`
+         if [ $? -eq 0 ]; then
+            break
+         else
+            sleep 1
+            retries=`expr $retries + 1`
+         fi
       done
-      if [ $loop -eq 61 ]; then
+      if [ $retries -eq 61 ]; then
          echo "Execd did not start in 61 seconds!"
          exit 1
       fi
