adopted stages

diff --git a/cluster/lcs/stage1 b/cluster/lcs/stage1
--- a/cluster/lcs/stage1
+++ b/cluster/lcs/stage1
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (C) 2001,2002,2003,2004,2005,2006,2007,2008 Andreas Lang-Nevyjel
+# Copyright (C) 2001,2002,2003,2004,2005,2006,2007,2008,2012 Andreas Lang-Nevyjel
 #
 # Send feedback to: <lang-nevyjel@init.at>
 #
@@ -51,7 +51,7 @@ fi
 
 which () {
     for p in /bin /sbin /usr/bin /usr/sbin ; do
-	[ -x ${p}/${1} ] && { echo "1" ; break ; }
+    [ -x ${p}/${1} ] && { echo "1" ; break ; }
     done
 }
 
@@ -69,29 +69,29 @@ set_hoststat () {
 }
 t_mother () {
     if [ ${motherserver:-0} = "0" ] ; then
-	echo ${echo_opt} "Server not set, can't connect to mother"
+        echo ${echo_opt} "Server not set, can't connect to mother"
     else
-	tell_mother -m $motherserver -p 8000 $@ || echo ${echo_opt} "Connection problem with mother"
+        tell_mother_zmq -m $motherserver -p 8000 $@ || echo ${echo_opt} "Connection problem with mother"
     fi
 }
 send_info () {
     if [ ${motherserver:-0} = "0" ] ; then
-	echo ${echo_opt} "Server not set, can't connect to mother"
+        echo ${echo_opt} "Server not set, can't connect to mother"
     else
-	tell_mother -m $motherserver -p 8000 -w "*$@" || echo ${echo_opt} "Connection problem with mother"
+        tell_mother_zmq -m $motherserver -p 8000 -w "*$@" || echo ${echo_opt} "Connection problem with mother"
     fi
 }
 
 get_conf_str () {
     num_retries=1
     while true ; do 
-	ret=`tell_mother -m $motherserver -p 8006 $1 2>&1`  && {
-	    state=`echo $ret | cut -d " " -f 1`
-	    [ "$state" = "ok" ] && break
-	}
-	echo ${echo_opt} >&2 "${RED}error (server $motherserver, port 8006, command $1, $ret), will sleep for 10 seconds${OFF}"
-	num_retries=$(($num_retries + 1))
-	sleep 10
+    ret=`tell_mother_zmq -m $motherserver -p 8006 $1 2>&1`  && {
+        state=`echo $ret | cut -d " " -f 1`
+        [ "$state" = "ok" ] && break
+    }
+    echo ${echo_opt} >&2 "${RED}error (server $motherserver, port 8006, command $1, $ret), will sleep for 10 seconds${OFF}"
+    num_retries=$(($num_retries + 1))
+    sleep 10
     done
     echo "$num_retries $ret"
 }
@@ -104,11 +104,11 @@ err_exit () {
     [ ! -d /dev/pts ] && mkdir /dev/pts
     logger $(mount -n -t devpts -o mode=0620,gid=5 devpts /dev/pts )
     if [ -x /usr/sbin/xinetd ] ; then
-	/usr/sbin/xinetd & 
+    /usr/sbin/xinetd & 
     elif [ -x /usr/sbin/inetd ] ; then
-	/usr/sbin/inetd &
+    /usr/sbin/inetd &
     else
-	echo ${echo_opt} "${RED}Neither xinetd nor inetd found${OFF}"
+    echo ${echo_opt} "${RED}Neither xinetd nor inetd found${OFF}"
     fi
     start_shell
 #  exit -1
@@ -126,33 +126,33 @@ boot_system () {
     mkdir -v initrd
     [ ! -c /$basedir/dev/console ] && mknod /$basedir/dev/console -m 0640 c 5 1
     if [ ! -x /$basedir/sbin/init ] ; then
-	err_exit "no executable /sbin/init in node-image" ;
+    err_exit "no executable /sbin/init in node-image" ;
     elif [ ! -f /$basedir/etc/inittab ] ; then
-	err_exit "no /etc/inittab in node-image" ;
+    err_exit "no /etc/inittab in node-image" ;
     elif [ ! -c /$basedir/dev/console ] ; then
-	err_exit "no /dev/console in node-image" ;
+    err_exit "no /dev/console in node-image" ;
     elif [ -x chroot ] ; then
-	echo ${echo_opt} "Shutting down ${valid_net}"
-	ifconfig ${valid_net} 0.0.0.0 down
-	cp -a /sbin/stage3 /$basedir/linuxrc
-	chmod +x /$basedir/linuxrc
-	# the exec is important
-	exec switch_root /$basedir linuxrc
-	# normally not reached if switch_root is working properly
-	pivot_root . initrd || {
-	    echo ${echo_opt} "${RED}Fatal: pivot_root . initrd failed ($?), trying run-init code ${OFF}"
-	    # run-init code
-	    exec /lib/mkinitrd/bin/run-init -c ./dev/console /$basedir /linuxrc 
-	    start_shell
-	}
-	cd /
-	umount initrd/proc
-	umount initrd/sys
-	
-	exec /chroot . /linuxrc < dev/console > dev/console 2>&1
+    echo ${echo_opt} "Shutting down ${valid_net}"
+    ifconfig ${valid_net} 0.0.0.0 down
+    cp -a /sbin/stage3 /$basedir/linuxrc
+    chmod +x /$basedir/linuxrc
+    # the exec is important
+    exec switch_root /$basedir linuxrc
+    # normally not reached if switch_root is working properly
+    pivot_root . initrd || {
+        echo ${echo_opt} "${RED}Fatal: pivot_root . initrd failed ($?), trying run-init code ${OFF}"
+        # run-init code
+        exec /lib/mkinitrd/bin/run-init -c ./dev/console /$basedir /linuxrc 
+        start_shell
+    }
+    cd /
+    umount initrd/proc
+    umount initrd/sys
+
+    exec /chroot . /linuxrc < dev/console > dev/console 2>&1
     else
-	echo ${echo_opt} "${RED}Fatal: Could not find chroot in node-image.${OFF}"
-	err_exit "no chroot in node-image"
+    echo ${echo_opt} "${RED}Fatal: Could not find chroot in node-image.${OFF}"
+    err_exit "no chroot in node-image"
     fi
 }
 
@@ -160,69 +160,69 @@ generate_devicefiles () {
     mknod /dev/tty c 5 0
     # generate ptys for debian
     for pty in $(seq 0 9) ; do 
-	mknod -m 0666 /dev/ttyp$pty c 3 $pty
+    mknod -m 0666 /dev/ttyp$pty c 3 $pty
     done
     # ptmx
     [ ! -c /dev/ptmx ] && mknod -m 0666 /dev/ptmx c 5 2
     [ ! -c /dev/urandom ] && mknod -m 0644 /dev/urandom c 1 9
     # IDE hds
     for dsk in hda:3:0 hdb:3:64 hdc:22:0 hdd:22:64 hde:33:0 hdf:33:64 hdg:34:0 hdh:34:64 ; do
-	bname=/dev/`echo $dsk | cut -d ":" -f 1`
-	major=`echo $dsk | cut -d ":" -f 2`
-	minor=`echo $dsk | cut -d ":" -f 3`
-	mknod -m 0600 $bname b $major $minor
-	for i in $(seq 31) ; do
-	    minor=$(( $minor + 1 ))
-	    mknod -m 0600 $bname$i b $major $minor
-	done
+    bname=/dev/`echo $dsk | cut -d ":" -f 1`
+    major=`echo $dsk | cut -d ":" -f 2`
+    minor=`echo $dsk | cut -d ":" -f 3`
+    mknod -m 0600 $bname b $major $minor
+    for i in $(seq 31) ; do
+        minor=$(( $minor + 1 ))
+        mknod -m 0600 $bname$i b $major $minor
+    done
     done
     # SCSI
     major=8
     minor=0
     for dsk in a b c d e f g h i j k l m n o p ; do
-	bname=/dev/sd$dsk
-	mknod -m 0600 $bname b $major $minor
-	for i in $(seq 15) ; do
-	    minor=$(( $minor + 1 ))
-	    mknod -m 0600 $bname$i b $major $minor
-	done
-	minor=$(( $minor + 1 ))
+    bname=/dev/sd$dsk
+    mknod -m 0600 $bname b $major $minor
+    for i in $(seq 15) ; do
+        minor=$(( $minor + 1 ))
+        mknod -m 0600 $bname$i b $major $minor
+    done
+    minor=$(( $minor + 1 ))
     done
     # Compaq CCISS
     cpq=/dev/cciss
     mkdir $cpq
     major=104
     for cac in 0 1 ; do
-	minor=0
-	bname=${cpq}/c${cac}
-	for dsk in $(seq 0 4) ; do 
-	    dname=${bname}d${dsk}
-	    mknod -m 0600 $dname b $major $minor
-	    minor=$(( $minor + 1 ))
-	    for i in $(seq 15) ; do
-		mknod -m 0600 ${dname}p$i b $major $minor
-		minor=$(( $minor + 1 ))
-	    done
-	done
-	major=$(( $major + 1 ))
+    minor=0
+    bname=${cpq}/c${cac}
+    for dsk in $(seq 0 4) ; do 
+        dname=${bname}d${dsk}
+        mknod -m 0600 $dname b $major $minor
+        minor=$(( $minor + 1 ))
+        for i in $(seq 15) ; do
+        mknod -m 0600 ${dname}p$i b $major $minor
+        minor=$(( $minor + 1 ))
+        done
+    done
+    major=$(( $major + 1 ))
     done
     # Compat IDA
     cpq=/dev/ida
     mkdir $cpq
     major=72
     for cac in 0 1 ; do
-	minor=0
-	bname=${cpq}/c${cac}
-	for dsk in $(seq 0 4) ; do
-	    dname=${bname}d${dsk}
-	    mknod -m 0600 $dname b $major $minor
-	    minor=$(( $minor + 1 ))
-	    for i in $(seq 15) ; do
-		mknod -m 0600 ${dname}p$i b $major $minor
-		minor=$(( $minor + 1 ))
-	    done
-	done
-	major=$(( $major + 1 ))
+    minor=0
+    bname=${cpq}/c${cac}
+    for dsk in $(seq 0 4) ; do
+        dname=${bname}d${dsk}
+        mknod -m 0600 $dname b $major $minor
+        minor=$(( $minor + 1 ))
+        for i in $(seq 15) ; do
+        mknod -m 0600 ${dname}p$i b $major $minor
+        minor=$(( $minor + 1 ))
+        done
+    done
+    major=$(( $major + 1 ))
     done
 }
 alias l='ls -alF'
@@ -232,6 +232,8 @@ alias ls='ls $LS_OPTIONS'
 alias ls-l='ls -l'
 alias ..='cd ..'
 alias ...='cd ../..'
+
+mkdir -p /etc/sysconfig/cluster
 
 echo "/dev/ram0 / ext2 rw 0 0 " >> /etc/mtab
 
@@ -262,9 +264,13 @@ generate_devicefiles
 
 [ -r /proc/cmdline ] && {
     for line in `cat /proc/cmdline` ; do
-	echo $line | grep "=" > /dev/null && eval $line ;
+        echo $line | grep "=" > /dev/null && eval $line ;
     done
 }
+
+echo "my UUID is '$uuid'"
+
+echo urn:uuid:$uuid > /etc/sysconfig/cluster/.cluster_device_uuid
 
 if [ ${ip:-0} = "0" ] ; then
     boottype="NET"
@@ -305,33 +311,33 @@ eth_neg_o=$((($ethtool_options-$((16*$eth_spd_o+4*$eth_dpl_o)))))
 eto=""
 case $eth_neg_o in
     1)
-	eto="$eto autoneg on"
-	;;
+    eto="$eto autoneg on"
+    ;;
     3)
-	eto="$eto autoneg off"
-	;;
+    eto="$eto autoneg off"
+    ;;
 esac
 case $eth_dpl_o in
     1)
-	eto="$eto duplex full"
-	;;
+    eto="$eto duplex full"
+    ;;
     3)
-	eto="$eto duplex half"
-	;;
+    eto="$eto duplex half"
+    ;;
 esac
 case $eth_spd_o in
     1)
-	eto="$eto speed 10"
-	;;
+    eto="$eto speed 10"
+    ;;
     3)
-	eto="$eto speed 100"
-	;;
+    eto="$eto speed 100"
+    ;;
     5)
-	eto="$eto speed 1000"
-	;;
+    eto="$eto speed 1000"
+    ;;
     7)
-	eto="$eto speed 10000"
-	;;
+    eto="$eto speed 10000"
+    ;;
 esac
 
 echo ${echo_opt} " netdevice given by server is ${nbd} (driver '$net_driver', options '$net_options', ethtool_options '$eto')"
@@ -358,14 +364,14 @@ initrd_mods=""
     echo -n "No available netdevices found, rebooting in 10 seconds"
     /sbin/lspci
     for i in $(seq 10) ; do 
-	echo -n "."
-	sleep 1
+    echo -n "."
+    sleep 1
     done
     /sbin/reboot -f
 }
 if echo $avail_nets | grep "${nbd}" > /dev/null 2>&1
 then
-  avail_nets=$(echo "${nbd} $(echo $nbd | sed -e "s/${nbd}//")")
+    avail_nets=$(echo "${nbd} $(echo $nbd | sed -e "s/${nbd}//")")
 fi
 
 
@@ -378,30 +384,34 @@ while true ; do
     valid_net="None"
 # check for valid netdevice
     for net in $avail_nets ; do
-	ifconfig ${net} ${ipaddr} netmask ${netmask} up
-	if [ $wait_time -gt 0 ] ; then
-	    sleep $wait_time
-	fi
-	[ -n "$eto" ] && { echo "applying ethtool-settings $eto to $net" ; ethtool -s ${net} $eto ; sleep $(($wait_time + 1)) ; }
-	ping -c $PING_PACKETS -w $PING_TIMEOUT -I ${net} $motherserver >/dev/null && {
-	    tell_mother -t 18 -m $motherserver -p 8000 "mother connection test" && {
-		echo ${echo_opt} "${GREEN}Server $motherserver reachable via ping and hoststatus over $net${OFF}" ;
-		valid_net=$net ;
-	    } || {
-		echo ${echo_opt} "${WARN}Server $motherserver reachable via ping over $net but no response to hoststatus (mother running ?)${OFF}" ;
-	    }
-	} || {
-	    echo ${echo_opt} "${RED}Server $motherserver not reachable via ping over $net${OFF}" ;
-	}
-	[ "${valid_net}" = "${nbd}" ] && break
-	ifconfig ${net} 0.0.0.0 down
+        ifconfig ${net} ${ipaddr} netmask ${netmask} up
+        if [ $wait_time -gt 0 ] ; then
+            sleep $wait_time
+        fi
+        [ -n "$eto" ] && {
+            echo "applying ethtool-settings $eto to $net" ;
+            ethtool -s ${net} $eto ;
+            sleep $(($wait_time + 1)) ;
+        }
+        ping -c $PING_PACKETS -w $PING_TIMEOUT -I ${net} $motherserver >/dev/null && {
+            tell_mother_zmq -t 18 -m $motherserver -p 8000 "mother connection test" && {
+                echo ${echo_opt} "${GREEN}Server $motherserver reachable via ping and hoststatus over $net${OFF}" ;
+                valid_net=$net ;
+            } || {
+                echo ${echo_opt} "${WARN}Server $motherserver reachable via ping over $net but no response to hoststatus (mother running ?)${OFF}" ;
+            }
+        } || {
+            echo ${echo_opt} "${RED}Server $motherserver not reachable via ping over $net${OFF}" ;
+        }
+        [ "${valid_net}" = "${nbd}" ] && break
+        ifconfig ${net} 0.0.0.0 down
     done
-    
+
     if [ "$valid_net" = "None" ] ; then
-	echo ${echo_opt} "${WARN}no response, increasing wait_time for 5 seconds and trying again...${OFF}"
-	wait_time=$(($wait_time + 5))
+        wait_time=$(($wait_time + 5))
+        echo ${echo_opt} "${WARN}no response, increasing wait_time for 5 seconds to ${wait_time} seconds, retry...${OFF}"
     else
-	break
+        break
     fi
 done
 
@@ -411,8 +421,8 @@ echo ${echo_opt} "Found netdevice $valid_net (needed $num_iters iterations)"
 if [ -f /etc/add_modules ] ; then
     echo ${echo_opt} "Loading additional modules specified in /etc/add_modules"
     while read module mod_option ; do
-	echo ${echo_opt} "Module $module (option $mod_option):"
-	modprobe $module $mod_option
+        echo ${echo_opt} "Module $module (option $mod_option):"
+        modprobe $module $mod_option
     done < /etc/add_modules
 fi
 
@@ -470,10 +480,10 @@ mount -t ramfs /dev/ram1 /stage2 || {
     ram_size=32768
     mkfs.ext2 -F -v -m 0 -b 1024 ${S2_RDISK} $ram_size >/tmp/errstr 2>&1 || {
         # second try, 16 MB (sigh)
-	ram_size=16384
-	mkfs.ext2 -F -v -m 0 -b 1024 ${S2_RDISK} $ram_size >/tmp/errstr 2>&1 || {
-	    err_exit "Cannot create stage2 RamDisc $(cat /tmp/errstr)" 
-	}
+    ram_size=16384
+    mkfs.ext2 -F -v -m 0 -b 1024 ${S2_RDISK} $ram_size >/tmp/errstr 2>&1 || {
+        err_exit "Cannot create stage2 RamDisc $(cat /tmp/errstr)" 
+    }
     }
 
     check_ram_fill=1
@@ -535,7 +545,7 @@ rm -f /stage2_result
 
 if [ "$check_ram_fill" = "1" ] ; then
     ram_fill=$(df ${S2_RDISK} | tail -1 | tr -s " " | cut -d " " -f 5 | tr -d "%")
-    
+
     [ $ram_fill -gt 98 ] && { err_exit "not enough space left in stage2: $ram_fill % full" ; }
 fi
 
