path fixes, compatibility fixes
git-svn-id: svn+ssh://repository/svn/clustersoftware@172 44af9490-3b78-11e1-98d3-d193acd27c9c

diff --git a/cluster/bin/make_image b/cluster/bin/make_image
--- a/cluster/bin/make_image
+++ b/cluster/bin/make_image
@@ -326,7 +326,7 @@ if [ "$BUILD" = "0" ] ; then
     echo -e "\n${RED}**** WARNING. *.bz2-files will not be generated ***${OFF}\n"
 fi
 
-/usr/local/sbin/check_image_packages.py ${check_package_options} -r $imsource || { [ "${IGNORE_ERRORS}" = "0" ] && { echo "packages missing, exiting..." ; exit -1 ; } }
+/opt/cluster/sbin/check_image_packages.py ${check_package_options} -r $imsource || { [ "${IGNORE_ERRORS}" = "0" ] && { echo "packages missing, exiting..." ; exit -1 ; } }
 if [ "$BUILD" = "1" ] ; then
     echo -n "Checking size of system: "
     if [ "$MODIFY_IMAGE" = "1" ] ; then
@@ -405,12 +405,12 @@ if [ "$BUILD" = "1" ] ; then
     fi
     echo
     echo "Inserting package information into database "
-    /usr/local/sbin/insert_package_info.py -r $sysdir -i $imidx ${check_package_options} 
+    /opt/cluster/sbin/insert_package_info.py -r $sysdir -i $imidx ${check_package_options} 
 else
     echo "Inserting package information into database "
-    /usr/local/sbin/insert_package_info.py -r $imsource -i $imidx ${check_package_options} 
+    /opt/cluster/sbin/insert_package_info.py -r $imsource -i $imidx ${check_package_options} 
 fi
-/usr/local/sbin/check_image_packages.py ${check_package_options} -i $imidx || { [ "${IGNORE_ERRORS}" = "0" ] && { echo "packages missing, exiting..." ; exit -1 ; } }
+/opt/cluster/sbin/check_image_packages.py ${check_package_options} -i $imidx || { [ "${IGNORE_ERRORS}" = "0" ] && { echo "packages missing, exiting..." ; exit -1 ; } }
 
 
 if [ "$BUILD" = "1" ] ; then
