stage1/2/3 improvements

diff --git a/cluster/bin/make_image b/cluster/bin/make_image
--- a/cluster/bin/make_image
+++ b/cluster/bin/make_image
@@ -16,22 +16,22 @@ print_usage () {
     echo ""
     echo "  $0 [-v] [-b] [-f] <image_name> [<compression_type>]"
     echo "  [-v]			be verbose"
-    echo "  [-b]			build .tar.(gz|bz2) files"
+    echo "  [-b]			build .tar.(gz|bz2|xz) files"
     echo "  [-f]			force being an image-server"
     echo "  [-i]			ignore package errors"
     echo "  [-M]			do not modify image (no chroot calls)"
     echo "  <image_name>		name of image to create"
-    echo "  [<compression_type>]	optional; type of compression to use (default: bz2)"
-    echo "			valid: gz bz2"
+    echo "  [<compression_type>]	optional; type of compression to use (default: xz)"
+    echo "			valid: gz bz2 xz"
     echo
     echo "Possible values for images are: $pimnames"
 }
 
 check_buildlock () {
     if [ $build_lock -ne $dev_idx ] && [ $build_lock -gt 0 ] ; then
-	lock_name=$(sql_query "SELECT d.name FROM device d WHERE d.device_idx=$build_lock") ;
-	echo "Image locked by other image server $lock_name ($build_lock)" ;
-	exit -2 ;
+        lock_name=$(sql_query "SELECT d.name FROM device d WHERE d.device_idx=$build_lock") ;
+        echo "Image locked by other image server $lock_name ($build_lock)" ;
+        exit -2 ;
     fi
 }
 
@@ -57,34 +57,34 @@ push_to_imageslaves () {
     net_idx=$(sql_query SELECT n.netdevice_idx FROM netdevice n WHERE n.device=$dev_idx)
     snet_str=""
     for idx in $net_idx ; do
-	snet_str="$snet_str OR h.s_netdevice=$idx"
+    snet_str="$snet_str OR h.s_netdevice=$idx"
     done
     if [ "${snet_str:-0}" != "0" ] ; then
-	snet_str="("${snet_str:4}")"
-	server_copied="$server_name+"
-	mnt_dir=`mktemp -d /tmp/.mount_XXXXXX`
-	sql_query "SELECT d.name, i.ip, h.value, i.alias FROM network nw, network_type nt, netip i INNER JOIN hopcount h INNER JOIN netdevice n INNER JOIN device d INNER JOIN device_config dc INNER JOIN new_config c INNER JOIN device_group dg LEFT JOIN device d2 ON d2.device_idx=dg.device WHERE i.network=nw.network_idx AND nt.network_type_idx=nw.network_type AND i.netdevice=n.netdevice_idx AND d.device_group=dg.device_group_idx AND ( $snet_str ) AND n.netdevice_idx=h.d_netdevice AND n.device=d.device_idx AND (dc.device=d2.device_idx OR dc.device=d.device_idx) AND dc.new_config=c.new_config_idx AND (c.name='image_server') AND nt.identifier='p' ORDER BY h.value, d.name " |
-		while read line ; do 
-		    sname=`echo $line| cut -d " " -f 1`
-		    mip=`echo $line| cut -d " " -f 2`
-		    value=`echo $line| cut -d " " -f 3`
-		    iname=`echo $line| cut -d " " -f 4`
-		    iname=${iname:-$sname}
-		    echo $server_copied | grep $sname\+ >/dev/null || {
-			echo "Copying image to server $sname (ip $mip, interfacename $iname, cost $value)";
-			server_copied="$server_copied $sname+"
-			mount -t nfs -v $mip:$imbasedir ${mnt_dir} && {
-			    rm -rf ${mnt_dir}/${imname}/*
-			    cp -a $imagedir ${mnt_dir}/.
-			    umount ${mnt_dir}
-			    mount $iname:$imversdir ${mnt_dir}
-			    cp -a $imversfile ${mnt_dir}/.
-			    umount ${mnt_dir}
-			    false
-			}
-		    }
-		done
-		rmdir ${mnt_dir}
+    snet_str="("${snet_str:4}")"
+    server_copied="$server_name+"
+    mnt_dir=`mktemp -d /tmp/.mount_XXXXXX`
+    sql_query "SELECT d.name, i.ip, h.value, i.alias FROM network nw, network_type nt, netip i INNER JOIN hopcount h INNER JOIN netdevice n INNER JOIN device d INNER JOIN device_config dc INNER JOIN new_config c INNER JOIN device_group dg LEFT JOIN device d2 ON d2.device_idx=dg.device WHERE i.network=nw.network_idx AND nt.network_type_idx=nw.network_type AND i.netdevice=n.netdevice_idx AND d.device_group=dg.device_group_idx AND ( $snet_str ) AND n.netdevice_idx=h.d_netdevice AND n.device=d.device_idx AND (dc.device=d2.device_idx OR dc.device=d.device_idx) AND dc.new_config=c.new_config_idx AND (c.name='image_server') AND nt.identifier='p' ORDER BY h.value, d.name " |
+        while read line ; do 
+            sname=`echo $line| cut -d " " -f 1`
+            mip=`echo $line| cut -d " " -f 2`
+            value=`echo $line| cut -d " " -f 3`
+            iname=`echo $line| cut -d " " -f 4`
+            iname=${iname:-$sname}
+            echo $server_copied | grep $sname\+ >/dev/null || {
+            echo "Copying image to server $sname (ip $mip, interfacename $iname, cost $value)";
+            server_copied="$server_copied $sname+"
+            mount -t nfs -v $mip:$imbasedir ${mnt_dir} && {
+                rm -rf ${mnt_dir}/${imname}/*
+                cp -a $imagedir ${mnt_dir}/.
+                umount ${mnt_dir}
+                mount $iname:$imversdir ${mnt_dir}
+                cp -a $imversfile ${mnt_dir}/.
+                umount ${mnt_dir}
+                false
+            }
+            }
+        done
+        rmdir ${mnt_dir}
     fi
 }
 
@@ -96,7 +96,7 @@ print_timestats () {
     rest=$(( $rest - ( $h * 3600 )))
     m=$(( $rest / 60 ))
     rest=$(( $rest - ( $m * 60 )))
-    
+
     echo "Took $d d $h h $m m $rest s"
 }
 
@@ -106,8 +106,8 @@ tftpdir=/tftpboot
 if [ ! -d $tftpdir ] ; then
     tftpdir=$(ls -d /*/${tftpdir} 2>/dev/null)
     if [ ! -d ${tftpdir:-0} ] ; then
-	echo "No tftpdir found"
-	exit -1
+    echo "No tftpdir found"
+    exit -1
     fi
 fi
 
@@ -118,7 +118,8 @@ imversdir=${imbasedir}/version_control
 
 [ ! -d "$imbasedir" ] && mkdir -p "$imbasedir"
 
-pimnames=$(sql_query "SELECT name FROM image ORDER BY name" | tr "\n" " ")
+pimnames=$(python-init -c  "from initat.cluster.backbone.models import image ; print ' '.join(image.objects.all().values_list('name', flat=True));")
+
 
 VERBOSE=0
 BUILD=0
@@ -135,13 +136,13 @@ set -- $args
 
 for i ; do
     case "$i" in
-	-v) shift ; VERBOSE=1 ;;
-	-b) shift ; BUILD=1 ;;
-	-f) shift ; FORCE=1 ;;
-	-i) shift ; IGNORE_ERRORS=1 ;;
-	-M) shift ; MODIFY_IMAGE=0 ;;
-	-h) shift ; print_usage ; exit -1 ;;
-	--) shift ; break ;;
+    -v) shift ; VERBOSE=1 ;;
+    -b) shift ; BUILD=1 ;;
+    -f) shift ; FORCE=1 ;;
+    -i) shift ; IGNORE_ERRORS=1 ;;
+    -M) shift ; MODIFY_IMAGE=0 ;;
+    -h) shift ; print_usage ; exit -1 ;;
+    --) shift ; break ;;
     esac
 done
 
@@ -161,7 +162,7 @@ if [ $# -ne 0 ] ; then
     echo "too many arguments";
     exit -1;
 fi
-    
+
 if [ $VERBOSE -gt 0 ] ; then
     debug () { echo $* ; }
     NULL=""
@@ -180,11 +181,11 @@ fi
 bm_stuff=`echo $(sql_query SELECT d.device_idx,d.name FROM device d, device_config dc, new_config c WHERE dc.new_config=c.new_config_idx AND dc.device=d.device_idx AND c.name=\'image_server\' AND d.name=\'$(hostname | cut -d "." -f 1)\')`
 if [ "${bm_stuff:-0}" = "0" ] ; then
     if [ "$FORCE" == "0" ] ; then
-	echo "${HOSTNAME} is not an image-server"
-	exit -1
+    echo "${HOSTNAME} is not an image-server"
+    exit -1
     else
-	dev_idx=1
-	server_name="unknown"
+    dev_idx=1
+    server_name="unknown"
     fi
 else
     dev_idx=`echo $bm_stuff| cut -d " " -f 1`
@@ -194,19 +195,24 @@ fi
 if [ "`echo $COMPRESSIONTYPE | grep gz 2> /dev/null`" ] ; then
     imcomptype='gz'
     tar_flags='-czf'
-else
+elif [ "`echo $COMPRESSIONTYPE | grep bz2 2> /dev/null`" ] ; then
     imcomptype='bz2'
-    tar_flags='-cjf'
+    tar_flags='-czf'
+else
+    imcomptype='xz'
+    tar_flags='-cJf'
     [ ".$COMPRESSIONTYPE" != "." ] && [ "$COMPRESSIONTYPE" != "$imcomptype" ] && echo "Bogus compression type '$COMPRESSIONTYPE', using '$imcomptype'"
 fi
 
-stuff=$(sql_query "SELECT source,version,\`release\`,builds,image_idx,build_lock FROM image WHERE name='${imname}'")
+stuff=$(python-init -c  "from initat.cluster.backbone.models import image ; print len(image.objects.filter(name='${imname}'));")
 
 #could not get info from image $imname
 if [ "${stuff:-0}" = "0" ] ; then
     echo "Wrong image name $imname, possible values are $pimnames." ;
     exit -1 ;
 fi
+
+stuff=$(python-init -c  "from initat.cluster.backbone.models import image ; img = image.objects.get(name='${imname}'); print ' '.join([img.source, str(img.version), str(img.release), str(img.builds), str(img.pk), '1' if img.build_lock else '0']);")
 
 imsource="`echo $stuff | cut -d " " -f 1`"
 imversion=`echo $stuff | cut -d " " -f 2`
@@ -270,11 +276,11 @@ if [ -f "${imsource}/etc/fedora-release" ] ; then
 elif [ -f "${imsource}/etc/redhat-release" ] ; then
     im_type="redhat"
     cat ${imsource}/etc/redhat-release | grep "Linux WS" > /dev/null && {
-	im_ver="3"
-	im_rel="0"
+    im_ver="3"
+    im_rel="0"
     } || {
-	im_ver="8"
-	im_rel="0"
+    im_ver="8"
+    im_rel="0"
     }
 elif [ -f "${imsource}/etc/debian_version" ] ; then
     im_type="debian"
@@ -315,10 +321,10 @@ nodir="proc@ media@ sys@"
 dlist=""
 for dir in $imsource/* ; do
     if [ -d $dir ] && [ ! -L $dir ] ; then
-	rdir=`basename $dir`
-	echo $nodir | grep ${rdir}@ > /dev/null || {
-	    dlist="$dlist $rdir" ;
-	}
+    rdir=`basename $dir`
+    echo $nodir | grep ${rdir}@ > /dev/null || {
+        dlist="$dlist $rdir" ;
+    }
     fi
 done
 
@@ -330,9 +336,9 @@ fi
 if [ "$BUILD" = "1" ] ; then
     echo -n "Checking size of system: "
     if [ "$MODIFY_IMAGE" = "1" ] ; then
-	chroot $imsource/  ${SHELL} -i -c 'umount proc' 2> /dev/null
+    chroot $imsource/  ${SHELL} -i -c 'umount proc' 2> /dev/null
     else
-	umount ${imsource}/proc
+    umount ${imsource}/proc
     fi
     debug "-en \n$imsource\t"
     imsource_size=$(du -sk "$imsource/." | cut -d'	' -f1)
@@ -342,70 +348,70 @@ if [ "$BUILD" = "1" ] ; then
     debug "-en \n$imagedir\t"
     imagedir_space=$(df -k "$imagedir/." | awk '$0 !~ /^Filesystem/{if(/^[[:space:]]/){print($3)}else{print($4);};}')
     echo -n "$imagedir_space kB, which "
-    
+
     if [ "$imsource_size" -ge "$imagedir_space" ] ; then
-	echo "is not enough."
-	echo "Please free up some space"
-	exit 1
+    echo "is not enough."
+    echo "Please free up some space"
+    exit 1
     else
     echo "should be enough"
     fi
-    
+
 # dlist2=""
     flist=`cd "$imsource" ; find ./{,.}* -type d -prune -o -print`
-    
-    
+
+
     debug "Directory list:$dlist"
     debug "     File list:$flist"
-    
+
     cd $sysdir
 
     echo 
     echo "Copying image:"
-    
+
     echo "Copying files from slash ..."
     for f in $flist ; do
-	cp -a $imsource/$f .
+    cp -a $imsource/$f .
     done
     for dir in $dlist ; do
-	echo "Copying dir $dir ..."
-	cp -a $imsource/$dir .
+    echo "Copying dir $dir ..."
+    cp -a $imsource/$dir .
     done
     echo
-    
+
     debug "Copying kernel and kernel modules to "$sysdir"..."
-    
+
     rm -rf boot/vmlinu* boot/System*
     rm -rf lib/modules/*
     if [ "$MODIFY_IMAGE" = "1" ] ; then
-		chroot . depmod -a 2> /dev/null
-		
-		if [ "${im_type}" = "suse" ] ; then
-			echo "Doing SuSEconfig..."
-			rm -f var/run/SuSEconfig-is-running var/lock/SuSEconfig-is-running
-			chroot . ${SHELL} -i -c '[ -n "`which SuSEconfig`" ] && SuSEconfig ; umount proc'"$NULL"
-		fi
-		
-		if [ "$imtype" = "normal" ] ; then
-			if [ "${im_type}" = "suse" ] ; then
-				debug "Disabling startup YaST call..."
-				rm -rf var/adm/setup/ 
-				echo "Fixing startup-scripts..."
-				chroot . ${SHELL} -c "for file in host-monitoring hoststatus child package-client loadmodules ; do [ -x etc/init.d/\$file ] && /sbin/insserv -d etc/rc.d/\$file ; done"
-			elif [ "${im_type}" = "redhat" -o "${im_type}" = "fedora" ] ; then
-				echo "Fixing startup-scripts..."
-				chroot . ${SHELL} -c "for file in host-monitoring hoststatus child package-client loadmodules ; do [ -x etc/init.d/\$file ] && /sbin/chkconfig \$file on ; done"
-			elif [ "${im_type}" = "debian" ] ; then
-				echo "Fixing startup-scripts..."
-				chroot . ${SHELL} -c "for file in host-monitoring hoststatus child package-client loadmodules ; do [ -x etc/init.d/\$file ] && /usr/sbin/update-rc.d \$file defaults ; done"
-			else
-				echo "no special fixup known for '${im_type}'."
-			fi
-		fi
+        chroot . depmod -a 2> /dev/null
+
+    if [ "${im_type}" = "suse" ] ; then
+        echo "Doing SuSEconfig..."
+        rm -f var/run/SuSEconfig-is-running var/lock/SuSEconfig-is-running
+        chroot . ${SHELL} -i -c '[ -n "`which SuSEconfig`" ] && SuSEconfig ; umount proc'"$NULL"
     fi
-    echo
-    echo "Inserting package information into database "
-    /opt/cluster/sbin/insert_package_info.py -r $sysdir -i $imidx ${check_package_options} 
+
+    if [ "$imtype" = "normal" ] ; then
+        if [ "${im_type}" = "suse" ] ; then
+            debug "Disabling startup YaST call..."
+            rm -rf var/adm/setup/ 
+            echo "Fixing startup-scripts..."
+            chroot . ${SHELL} -c "for file in host-monitoring hoststatus child package-client loadmodules ; do [ -x etc/init.d/\$file ] && /sbin/insserv -d etc/rc.d/\$file ; done"
+        elif [ "${im_type}" = "redhat" -o "${im_type}" = "fedora" ] ; then
+            echo "Fixing startup-scripts..."
+            chroot . ${SHELL} -c "for file in host-monitoring hoststatus child package-client loadmodules ; do [ -x etc/init.d/\$file ] && /sbin/chkconfig \$file on ; done"
+        elif [ "${im_type}" = "debian" ] ; then
+            echo "Fixing startup-scripts..."
+            chroot . ${SHELL} -c "for file in host-monitoring hoststatus child package-client loadmodules ; do [ -x etc/init.d/\$file ] && /usr/sbin/update-rc.d \$file defaults ; done"
+        else
+            echo "no special fixup known for '${im_type}'."
+        fi
+    fi
+fi
+echo
+echo "Inserting package information into database "
+/opt/cluster/sbin/insert_package_info.py -r $sysdir -i $imidx ${check_package_options} 
 else
     echo "Inserting package information into database "
     /opt/cluster/sbin/insert_package_info.py -r $imsource -i $imidx ${check_package_options} 
@@ -416,43 +422,43 @@ fi
 if [ "$BUILD" = "1" ] ; then
     echo "Compressing image..."
     test -f "$imsource/../${imname}.excl" || > $imsource/../${imname}.excl
-    
+
     size_string=""
-    
+
     for dir in $dlist ; do
-	tarfile=$imagedir/$dir.tar
-	bzfile=$imagedir/$dir.tar.$imcomptype
-	dirsize=`du -ks $dir | cut -f 1`
-	size_string=${size_string}${dir}\;${dirsize}\;
-	echo "Compressing $dir ($dirsize k) to new $bzfile "
-	rm -f "$bzfile" "$tarfile"*
-	if [ "${im_type}" = "debian" ] ; then
-	    extra_flags="--numeric-owner"
-	else
-	    extra_flags=""
-	fi
-	(tar -X $imsource/../${imname}.excl $extra_flags $tar_flags $bzfile --preserve-permissions --preserve-order $dir || { echo "Encountered error $?, exiting" ; exit -1 ; }) 2>&1 >&1 | grep -v "socket ignored"
-    done
-    
-    if test -n "$flist" ; then
-	tarfile=$imagedir/slash.tar
-	bzfile=$imagedir/slash.tar.$imcomptype
-	dirsize=0
-	dirsize='$(( '`du -sk $flist | awk '{printf($1" + ")}'`"$dirsize ))"
-	eval dirsize=$dirsize
-	size_string=${size_string}slash\;${dirsize}\;
-	echo "Compressing slash ($dirsize k) to new $bzfile ..."
-	rm -f "$bzfile" "$tarfile"*
-	tar -X $imsource/../${imname}.excl $tar_flags $bzfile --preserve-permissions --preserve-order $flist || { echo "Encountered error $?, exiting" ; exit -1 ; }
+    tarfile=$imagedir/$dir.tar
+    bzfile=$imagedir/$dir.tar.$imcomptype
+    dirsize=`du -ks $dir | cut -f 1`
+    size_string=${size_string}${dir}\;${dirsize}\;
+    echo "Compressing $dir ($dirsize k) to new $bzfile "
+    rm -f "$bzfile" "$tarfile"*
+    if [ "${im_type}" = "debian" ] ; then
+        extra_flags="--numeric-owner"
     else
-	rm -f $imagedir/slash.tar.$imcomptype
+        extra_flags=""
+    fi
+    (tar -X $imsource/../${imname}.excl $extra_flags $tar_flags $bzfile --preserve-permissions --preserve-order $dir || { echo "Encountered error $?, exiting" ; exit -1 ; }) 2>&1 >&1 | grep -v "socket ignored"
+    done
+
+    if test -n "$flist" ; then
+    tarfile=$imagedir/slash.tar
+    bzfile=$imagedir/slash.tar.$imcomptype
+    dirsize=0
+    dirsize='$(( '`du -sk $flist | awk '{printf($1" + ")}'`"$dirsize ))"
+    eval dirsize=$dirsize
+    size_string=${size_string}slash\;${dirsize}\;
+    echo "Compressing slash ($dirsize k) to new $bzfile ..."
+    rm -f "$bzfile" "$tarfile"*
+    tar -X $imsource/../${imname}.excl $tar_flags $bzfile --preserve-permissions --preserve-order $flist || { echo "Encountered error $?, exiting" ; exit -1 ; }
+    else
+    rm -f $imagedir/slash.tar.$imcomptype
     fi
 else
     size_string=""
-    
+
     for dir in $dlist ; do
-	dirsize=`du -ks $imsource/$dir | cut -f 1`
-	size_string=${size_string}${dir}\;${dirsize}\;
+    dirsize=`du -ks $imsource/$dir | cut -f 1`
+    size_string=${size_string}${dir}\;${dirsize}\;
     done
 fi
 
@@ -478,14 +484,14 @@ if [ "$BUILD" = "1" ] ; then
     tdir=`mktemp -d /tmp/tdir_XXXXXX`
     typefile=${imagedir}/.tdir.tar
     for dir in $dlist ; do 
-	touch ${tdir}/${dir}
-	chmod --reference=$sysdir/$dir ${tdir}/${dir}
-	chown --reference=$sysdir/$dir ${tdir}/${dir}
+    touch ${tdir}/${dir}
+    chmod --reference=$sysdir/$dir ${tdir}/${dir}
+    chown --reference=$sysdir/$dir ${tdir}/${dir}
     done
     pushd . > /dev/null
     cd $tdir
     rm -f "$typefile"*
-    
+
     tar $tar_flags $typefile.$imcomptype *
     cd $imagedir
     rm -rf $tdir
@@ -497,7 +503,8 @@ rm -rf "$sysdir" && echo "."
 echo -en "\nSyncing discs.."
 sync && echo ". done"
 
-push_to_imageslaves
+echo "push_to_imageslaves not implemented, FIXME"
+#push_to_imageslaves
 
 unset_lock
 
diff --git a/cluster/lcs/stage1 b/cluster/lcs/stage1
--- a/cluster/lcs/stage1
+++ b/cluster/lcs/stage1
@@ -1,4 +1,5 @@
 #!/bin/bash
+# -*-  indent-tabs-mode:nil;  -*- 
 #
 # Copyright (C) 2001,2002,2003,2004,2005,2006,2007,2008,2012 Andreas Lang-Nevyjel
 #
@@ -85,13 +86,13 @@ send_info () {
 get_conf_str () {
     num_retries=1
     while true ; do 
-    ret=`tell_mother_zmq -i $ipaddr -m $motherserver -p 8005 $1 2>&1`  && {
-        state=`echo $ret | cut -d " " -f 1`
-        [ "$state" = "ok" ] && break
-    }
-    echo ${echo_opt} >&2 "${RED}error (server $motherserver, port 8005, command $1, $ret), will sleep for 10 seconds${OFF}"
-    num_retries=$(($num_retries + 1))
-    sleep 10
+        ret=`tell_mother_zmq -i $ipaddr -m $motherserver -p 8005 $1 2>&1`  && {
+            state=`echo $ret | cut -d " " -f 1`
+            [ "$state" = "ok" ] && break
+        }
+        echo ${echo_opt} >&2 "${RED}error (server $motherserver, port 8005, command $1, $ret), will sleep for 10 seconds${OFF}"
+        num_retries=$(($num_retries + 1))
+        sleep 10
     done
     echo "$num_retries $ret"
 }
@@ -104,11 +105,11 @@ err_exit () {
     [ ! -d /dev/pts ] && mkdir /dev/pts
     logger $(mount -n -t devpts -o mode=0620,gid=5 devpts /dev/pts )
     if [ -x /usr/sbin/xinetd ] ; then
-    /usr/sbin/xinetd & 
+        /usr/sbin/xinetd & 
     elif [ -x /usr/sbin/inetd ] ; then
-    /usr/sbin/inetd &
+        /usr/sbin/inetd &
     else
-    echo ${echo_opt} "${RED}Neither xinetd nor inetd found${OFF}"
+        echo ${echo_opt} "${RED}Neither xinetd nor inetd found${OFF}"
     fi
     start_shell
 #  exit -1
@@ -126,20 +127,20 @@ boot_system () {
     mkdir -v initrd
     [ ! -c /$basedir/dev/console ] && mknod /$basedir/dev/console -m 0640 c 5 1
     if [ ! -x /$basedir/sbin/init ] ; then
-    err_exit "no executable /sbin/init in node-image" ;
+        err_exit "no executable /sbin/init in node-image" ;
     elif [ ! -f /$basedir/etc/inittab ] ; then
-    err_exit "no /etc/inittab in node-image" ;
+        err_exit "no /etc/inittab in node-image" ;
     elif [ ! -c /$basedir/dev/console ] ; then
-    err_exit "no /dev/console in node-image" ;
+        err_exit "no /dev/console in node-image" ;
     elif [ -x chroot ] ; then
-    echo ${echo_opt} "Shutting down ${valid_net}"
-    ifconfig ${valid_net} 0.0.0.0 down
-    cp -a /sbin/stage3 /$basedir/linuxrc
-    chmod +x /$basedir/linuxrc
-    # the exec is important
-    exec switch_root /$basedir linuxrc
-    # normally not reached if switch_root is working properly
-    pivot_root . initrd || {
+        echo ${echo_opt} "Shutting down ${valid_net}"
+        ifconfig ${valid_net} 0.0.0.0 down
+        cp -a /sbin/stage3 /$basedir/linuxrc
+        chmod +x /$basedir/linuxrc
+        # the exec is important
+        exec switch_root /$basedir linuxrc
+        # normally not reached if switch_root is working properly
+        pivot_root . initrd || {
         echo ${echo_opt} "${RED}Fatal: pivot_root . initrd failed ($?), trying run-init code ${OFF}"
         # run-init code
         exec /lib/mkinitrd/bin/run-init -c ./dev/console /$basedir /linuxrc 
@@ -151,8 +152,8 @@ boot_system () {
 
     exec /chroot . /linuxrc < dev/console > dev/console 2>&1
     else
-    echo ${echo_opt} "${RED}Fatal: Could not find chroot in node-image.${OFF}"
-    err_exit "no chroot in node-image"
+        echo ${echo_opt} "${RED}Fatal: Could not find chroot in node-image.${OFF}"
+        err_exit "no chroot in node-image"
     fi
 }
 
@@ -160,69 +161,69 @@ generate_devicefiles () {
     mknod /dev/tty c 5 0
     # generate ptys for debian
     for pty in $(seq 0 9) ; do 
-    mknod -m 0666 /dev/ttyp$pty c 3 $pty
+        mknod -m 0666 /dev/ttyp$pty c 3 $pty
     done
     # ptmx
     [ ! -c /dev/ptmx ] && mknod -m 0666 /dev/ptmx c 5 2
     [ ! -c /dev/urandom ] && mknod -m 0644 /dev/urandom c 1 9
     # IDE hds
     for dsk in hda:3:0 hdb:3:64 hdc:22:0 hdd:22:64 hde:33:0 hdf:33:64 hdg:34:0 hdh:34:64 ; do
-    bname=/dev/`echo $dsk | cut -d ":" -f 1`
-    major=`echo $dsk | cut -d ":" -f 2`
-    minor=`echo $dsk | cut -d ":" -f 3`
-    mknod -m 0600 $bname b $major $minor
-    for i in $(seq 31) ; do
-        minor=$(( $minor + 1 ))
-        mknod -m 0600 $bname$i b $major $minor
-    done
+        bname=/dev/`echo $dsk | cut -d ":" -f 1`
+        major=`echo $dsk | cut -d ":" -f 2`
+        minor=`echo $dsk | cut -d ":" -f 3`
+        mknod -m 0600 $bname b $major $minor
+        for i in $(seq 31) ; do
+            minor=$(( $minor + 1 ))
+            mknod -m 0600 $bname$i b $major $minor
+        done
     done
     # SCSI
     major=8
     minor=0
     for dsk in a b c d e f g h i j k l m n o p ; do
-    bname=/dev/sd$dsk
-    mknod -m 0600 $bname b $major $minor
-    for i in $(seq 15) ; do
+        bname=/dev/sd$dsk
+        mknod -m 0600 $bname b $major $minor
+        for i in $(seq 15) ; do
+            minor=$(( $minor + 1 ))
+            mknod -m 0600 $bname$i b $major $minor
+        done
         minor=$(( $minor + 1 ))
-        mknod -m 0600 $bname$i b $major $minor
-    done
-    minor=$(( $minor + 1 ))
     done
     # Compaq CCISS
     cpq=/dev/cciss
     mkdir $cpq
     major=104
     for cac in 0 1 ; do
-    minor=0
-    bname=${cpq}/c${cac}
-    for dsk in $(seq 0 4) ; do 
-        dname=${bname}d${dsk}
-        mknod -m 0600 $dname b $major $minor
-        minor=$(( $minor + 1 ))
-        for i in $(seq 15) ; do
-        mknod -m 0600 ${dname}p$i b $major $minor
-        minor=$(( $minor + 1 ))
+        minor=0
+        bname=${cpq}/c${cac}
+        for dsk in $(seq 0 4) ; do 
+            dname=${bname}d${dsk}
+            mknod -m 0600 $dname b $major $minor
+            minor=$(( $minor + 1 ))
+            for i in $(seq 15) ; do
+                mknod -m 0600 ${dname}p$i b $major $minor
+                minor=$(( $minor + 1 ))
+            done
         done
-    done
-    major=$(( $major + 1 ))
+        major=$(( $major + 1 ))
     done
     # Compat IDA
     cpq=/dev/ida
     mkdir $cpq
     major=72
     for cac in 0 1 ; do
-    minor=0
-    bname=${cpq}/c${cac}
-    for dsk in $(seq 0 4) ; do
-        dname=${bname}d${dsk}
-        mknod -m 0600 $dname b $major $minor
-        minor=$(( $minor + 1 ))
-        for i in $(seq 15) ; do
-        mknod -m 0600 ${dname}p$i b $major $minor
-        minor=$(( $minor + 1 ))
+        minor=0
+        bname=${cpq}/c${cac}
+        for dsk in $(seq 0 4) ; do
+            dname=${bname}d${dsk}
+            mknod -m 0600 $dname b $major $minor
+            minor=$(( $minor + 1 ))
+            for i in $(seq 15) ; do
+                mknod -m 0600 ${dname}p$i b $major $minor
+                minor=$(( $minor + 1 ))
+            done
         done
-    done
-    major=$(( $major + 1 ))
+        major=$(( $major + 1 ))
     done
 }
 alias l='ls -alF'
@@ -311,33 +312,33 @@ eth_neg_o=$((($ethtool_options-$((16*$eth_spd_o+4*$eth_dpl_o)))))
 eto=""
 case $eth_neg_o in
     1)
-    eto="$eto autoneg on"
-    ;;
+        eto="$eto autoneg on"
+        ;;
     3)
-    eto="$eto autoneg off"
-    ;;
+        eto="$eto autoneg off"
+        ;;
 esac
 case $eth_dpl_o in
     1)
-    eto="$eto duplex full"
-    ;;
+        eto="$eto duplex full"
+        ;;
     3)
-    eto="$eto duplex half"
-    ;;
+        eto="$eto duplex half"
+        ;;
 esac
 case $eth_spd_o in
     1)
-    eto="$eto speed 10"
-    ;;
+        eto="$eto speed 10"
+        ;;
     3)
-    eto="$eto speed 100"
-    ;;
+        eto="$eto speed 100"
+        ;;
     5)
-    eto="$eto speed 1000"
-    ;;
+        eto="$eto speed 1000"
+        ;;
     7)
-    eto="$eto speed 10000"
-    ;;
+        eto="$eto speed 10000"
+        ;;
 esac
 
 echo ${echo_opt} " netdevice given by server is ${nbd} (driver '$net_driver', options '$net_options', ethtool_options '$eto')"
